name: CI-PR

on: [pull_request]

jobs:
  clang-format:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: clang-format
      run: |
        docker run --rm -v ${PWD}:/src ghcr.io/wiiu-env/clang-format:13.0.0-2 -r ./source ./include
  build-lib:
    runs-on: ubuntu-22.04
    needs: clang-format
    steps:
    - uses: actions/checkout@v3
    - name: build lib
      run: |
        docker build . -t tmp
        docker build . -f Dockerfile.buildlocal -t builder        
        docker run --rm -v ${PWD}:/project builder make
        docker run --rm -v ${PWD}:/project builder /bin/bash -c "make install && chmod +x tests/parameter_checker/runner.sh && cd tests/parameter_checker && ./runner.sh"
        docker run --rm -v ${PWD}:/project builder /bin/bash -c "make install && chmod +x tests/parameter_checker/negative_runner.sh && cd tests/parameter_checker && ./negative_runner.sh"
    - uses: actions/upload-artifact@master
      with:
       name: lib
       path: "lib/*.a"